cte/support_with_recursive
sqlfluff/sqlfluff pull request #1102
Opened 2021-05-26 08:42 UTC by bolajiwahab

2021-05-26 08:55 UTC, bolajiwahab commented
Fixes issue https://github.com/sqlfluff/sqlfluff/issues/1087

2021-05-26 09:16 UTC, bolajiwahab commented
@alanmcruickshank Think we can merge this now?

2021-05-26 15:11 UTC, NiallRees commented on src/sqlfluff/dialects/dialect_ansi.py
> +        Sequence("RECURSIVE", optional=True),
```suggestion
        Ref.keyword("RECURSIVE", optional=True),
```

2021-05-26 15:12 UTC, NiallRees requested changes
This is great @bolajiwahab - just a small change needed!

2021-05-27 22:42 UTC, NiallRees approved these changes

2021-05-27 23:22 UTC, merged