Add get diagnostic syntax to mysql dialect
sqlfluff/sqlfluff pull request #1179
Opened 2021-07-05 12:00 UTC by silverbullettruck2001

I also added 2 tests for code that I previously committed and was merged (`function_definer` and `procedure_definer`)

2021-07-05 14:02 UTC, barrywhart approved these changes
Looks good! A couple of observations, but nothing to hold up merging.

2021-07-05 14:03 UTC, barrywhart commented
@silverbullettruck2001: Can you fix the `CHANGELOG.md` conflicts? Otherwise, this is good to merge. I'll be "away from keyboard" for a few days. Feel free to tag another maintainer to merge it.

2021-07-05 14:56 UTC, barrywhart requested changes
Small issue with the change log

2021-07-06 20:37 UTC, silverbullettruck2001 commented on CHANGELOG.md
> +- Support for select statement syntax specific to mysql dialect [#1175](https://github.com/sqlfluff/sqlfluff/issues/1175)
@barrywhart These duplicate lines have been removed.

2021-07-06 20:41 UTC, barrywhart approved these changes

2021-07-09 01:37 UTC, merged