Issue 1321: Handle Jinja leading whitespace-only lines
sqlfluff/sqlfluff pull request #1364
Opened 2021-09-07 17:37 UTC by barrywhart

_Firstly, thanks for adding this feature! Secondly, please check the key steps against the checklist below to make your contribution easy to merge._

_Please give the Pull Request a meaningful title (including the dialect this PR is for if it is dialect specific), as this will automatically be added to the release notes, and then the Change Log._

### Brief summary of the change made
_If there is an open issue for this, then please include `fixes #XXXX` or `closes #XXXX` replacing `XXXX` with the issue number and it will automatically close the issue when the pull request is merged. Alternatively if not fully closed you can say `makes progress on #XXXX` to create a link on that issue without closing it._
...

### Are there any other side effects of this change that we should be aware of?
...

Fixes #1321 
Preserves leading whitespace-only lines in SQL files when the Jinja templater is used.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` locally).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2021-09-07 18:28 UTC, barrywhart commented
The CircleCI steps won't run until next week or we get the usage limits raised/removed, whichever comes first.

2021-09-07 18:36 UTC, tunetheweb approved these changes

2021-09-07 18:43 UTC, tunetheweb requested changes
Actually going to un-approve as using non-collapsing whitespace now breaks, whereas previously it worked.

Example:

```sql



{% set x = 42 %}
SELECT 1,2
```

Now returns:

```sql



{% set x = 42 %}
SELSELECT
1,
2
```

Because we're now adding the whitespace twice with this change.

I think it's best to just say we don't support `{%-` and `-%}` for now,

2021-09-07 19:02 UTC, tunetheweb commented on src/sqlfluff/core/templaters/jinja.py
> +        for _, elem_type, raw in lex(env, in_str):
Actually I found a real cheeky fix that seems to work for both #1321 and #854 now you've done the hard work and led the way:

```suggestion

        # Using Jinja whitespace stripping (e.g. `{#-` or `-%}`) breaks the
        # position markers between unlexed and lexed file. So let's ignore any
        # request to do that before lexing, by replacing '-' with '+'
        #
        # Note: '+' is the default, so shouldn't really be needed but we
        # explicitly state that to preserve the space for the missing '-' character
        # so it looks the same.
        in_str = in_str.replace('{%-', '{%+')
        in_str = in_str.replace('-%}', '+%}')
        in_str = in_str.replace('{#-', '{#+')
        in_str = in_str.replace('-#}', '+#}')

        for _, elem_type, raw in env.lex(env, in_str):
```

If so we should remove the `re` import above as no longer needed and also enhance this with other test cases (the example above I suggested and the one from #854).

2021-09-07 21:13 UTC, tunetheweb approved these changes
One small fix (without which CI won't pass anyway I don't think) but other than that this LGTM!

2021-09-07 21:13 UTC, tunetheweb commented on src/sqlfluff/core/templaters/python.py
> +                            cur_idx = 0  # pragma: noqa
```suggestion
                            cur_idx = 0  # pragma: no cover
```

2021-09-09 11:57 UTC, tunetheweb requested changes

2021-09-09 11:57 UTC, tunetheweb commented on src/sqlfluff/core/templaters/jinja.py
> +        in_str = in_str.replace("-#}", "+#}")
Looks like dbt doesn't need this workaround and inherits this, so need to stick an `if` check in here:

```suggestion
        #
        # Note dbt inherits this class and does not need this workaround
        if cls.name == "jinja":
            in_str = in_str.replace("{%-", "{%+")
            in_str = in_str.replace("-%}", "+%}")
            in_str = in_str.replace("{#-", "{#+")
            in_str = in_str.replace("-#}", "+#}")
```

2021-09-09 14:18 UTC, barrywhart commented
I dug through the voluminous log for that failed test. I think this is the error:
```
Line is too long
```

So... I wonder if dbt would also benefit from this fix, but a side effect of our fix is that the post-rendered code has a line that is too long. Note there is a [known issue](https://github.com/sqlfluff/sqlfluff/issues/845) where SQLFluff incorrectly checks line length after template expansion, not before.

Would you be okay if I tweaked that test to ignore "line too long" errors? Since most of our users use dbt, I hate to deliberately not fix a nasty bug that is likely to affect them. Happy to loop in another maintainer who is more familiar with dbt if you think that's wise. I am just a Jinja person myself. 🙂

2021-09-09 14:23 UTC, tunetheweb commented
SGTM

2021-09-09 15:34 UTC, barrywhart commented
@NiallRees: With the changes in this PR, one of the dbt tests is failing for reasons I don't understand -- L003 is reporting an issue. I am not familiar with the dbt templater. I think this fix is important both for jinja and for dbt, so I'd like to have both templaters use this fix if we are confident it's working okay.

2021-09-10 00:20 UTC, barrywhart commented on src/sqlfluff/core/templaters/dbt.py
> +            if e.node:
This change fixes an unrelated bug I discovered: For some errors, a `DbtCompilationException` object has a `node` value of `None`, in which case referencing `e.node.original_file_path` fails. Worse, this prevents the user from seeing the original error message.

2021-09-10 01:10 UTC, tunetheweb approved these changes

2021-09-10 01:17 UTC, merged

2021-09-10 07:51 UTC, CyberShadow commented
Thank you!

I tried this on our codebase and this seems to be the next problem: https://github.com/sqlfluff/sqlfluff/issues/1371