L029: Check quoted identifiers in addition to naked identifiers
sqlfluff/sqlfluff pull request #1775
Opened 2021-10-28 19:48 UTC by jpers36

Fixes #1747

This PR adjusts L029 to optionally check quoted identifiers in addition to naked identifiers.
In order to do this, we are adding a new configuration keyword, quoted_identifiers_policy, which represents the same thing as unquoted_identifiers_policy but for quoted identifiers.
The options for quoted_identifiers_policy are the same as unquoted_identifiers_policy with the addition of none, representing no checks for quoted identifiers.

We check quoted identifiers by stripping off the first and last character.  If we have a case where this shortcut would fail, we'll need to tweak the code before merging.

Changes:
+quoted_identifiers_policy default of none to default_config.cfg
+quoted_identifiers_policy description in config_info.py
L014.py: Rename unquoted_ids_policy_applicable function to identifiers_policy_applicable in order to reflect change in functionality
L029.py: Reflect renaming of unquoted_ids_policy_applicable function; add quoted_identifiers_policy as a configuration keyword; adjust rule to check quoted identifiers based on the config setting.
L029.yml: Rename test cases to be more descriptive.  Add quoted identifier test cases.

2021-10-29 18:36 UTC, barrywhart reviewed
One small suggestion, but looks pretty good to me.

@tunetheweb: Would you like to review as well? Holding off approving until I hear from you.

2021-10-29 18:36 UTC, barrywhart commented on src/sqlfluff/rules/L014.py
> +    """Does `(un)quoted_identifiers_policy` apply to this segment?"""
While not strictly necessary, I wonder if we may want to add:
```
if policy == "none":
    return False
```

That would make the code easier to understand and potentially a bit faster.

2021-10-29 18:46 UTC, tunetheweb commented
> @tunetheweb: Would you like to review as well? Holding off approving until I hear from you.

Won’t be near a computer for next few days so happy to go with your approval.

One slight nit from a quick look on phone is all test cases are t-sql, which uses different quotes than most. Might be good to have one ANSI I’ve too. But other than that great set of test cases.

2021-10-29 18:49 UTC, barrywhart commented
@jpers36: The other reviewer suggested adding at least one test case that doesn't use TSQL. Could you add an ANSI test case to address that?

This raises another question -- are there any databases where quotes are more than one character long? If so, code like this wouldn't work correctly:
```
context.segment.raw.upper()[1:-1]
```

2021-10-29 18:50 UTC, barrywhart requested changes
Request for one new test case. Also a potential question about potentially other dialects using oddball quotes.

2021-10-31 19:51 UTC, tunetheweb approved these changes
Think this is good to merge. @barrywhart anything holding it up from your end?

2021-10-31 22:05 UTC, barrywhart approved these changes

2021-10-31 23:56 UTC, merged