[many dialects] Add support for SQLAlchemy templating
sqlfluff/sqlfluff pull request #1878
Opened 2021-11-10 18:34 UTC by jacopofar

### Brief summary of the change made
This closes in #1216 by adding support for the SQLAlchemy parameter passing. SQLALchemy is a very common library to interface with DBs and it supports multiple engines (e.g. Postgres, MySQL, SQLite, etc.)

### Are there any other side effects of this change that we should be aware of?
Not that I can see, the usage is identical to the other templaters but much simpler

### Pull Request checklist
- [X ] Please confirm you have completed any of the necessary steps below.

2021-11-11 09:16 UTC, WittierDinosaur commented
Probably one for @barrywhart or @alanmcruickshank to review

2021-11-11 14:28 UTC, barrywhart approved these changes
Other than a typo in a variable name, looks great!

Hypothetically, how much effort would it be to make this templater more generic, e.g. so we could subclass it to handle other templating syntax? For example, see #1871.

2021-11-11 14:28 UTC, barrywhart commented on src/sqlfluff/core/templaters/sqlalchemy.py
> +            start_teplate_pos = last_pos_templated + last_literal_length
```suggestion
            start_template_pos = last_pos_templated + last_literal_length
```

2021-11-11 14:28 UTC, barrywhart commented on src/sqlfluff/core/templaters/sqlalchemy.py
> +                        start_teplate_pos, start_teplate_pos + len(replacement), None
```suggestion
                        start_template_pos, start_template_pos + len(replacement), None
```

2021-11-11 14:28 UTC, barrywhart commented on src/sqlfluff/core/templaters/sqlalchemy.py
> +            last_pos_templated = start_teplate_pos + len(replacement)
```suggestion
            last_pos_templated = start_template_pos + len(replacement)
```

2021-11-11 14:29 UTC, barrywhart requested changes
Changing review to "request changes" so we can fix the typos before merging.

2021-11-11 15:06 UTC, jacopofar commented on src/sqlfluff/core/templaters/sqlalchemy.py
> +            start_teplate_pos = last_pos_templated + last_literal_length
fixed

2021-11-11 15:06 UTC, jacopofar commented on src/sqlfluff/core/templaters/sqlalchemy.py
> +            last_pos_templated = start_teplate_pos + len(replacement)
done

2021-11-11 15:15 UTC, barrywhart approved these changes

2021-11-11 15:24 UTC, barrywhart commented
@jacopofar: If you're up for making that change, that would be great! Do you think it'd be better to do that in this or in a separate PR?

2021-11-11 15:26 UTC, jacopofar commented
we can close this and I'll open a separate request for that, should be easy to change

2021-11-11 15:37 UTC, barrywhart commented
Ok, merging now. For reference, issue #1871 would hopefully be easy to implement after making this templater more generic.

2021-11-11 15:37 UTC, merged

2021-11-12 08:03 UTC, jacopofar commented
oh sorry by close I meant without merging, since the new one will replace it completely and break the (unlikely) code already using it

2021-11-12 13:31 UTC, barrywhart commented
Oh, I'm sorry. Well, it's not in a release yet, so it's fine to change. It should be possible (assuming we want to) to keep it compatible (I.e. same templater name in the config file).