Migrate issue template from markdown to yaml
sqlfluff/sqlfluff pull request #2626
Opened 2022-02-13 13:34 UTC by zhongjiajie

Change issue template to yaml make our issue form
more user friendly, and also make our issue structured.
It have some rule to make sure user have to fill
before they submit issue.

See more detail in
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

2022-02-13 18:17 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +        This is absolutely not required, but we are happy to guide you in the contribution process
```suggestion
        This is absolutely not required, but we are happy to guide you in the contribution process,
```

2022-02-13 18:18 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/documentation.yml
> +            I had searched in the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found
Same suggestion as for the bug template.

2022-02-13 18:18 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/documentation.yml
> +      label: Are you willing to submit PR?
Same suggestion as for the bug template.

2022-02-13 18:19 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/enhancement.yml
> +      description: A short description of your feature
```suggestion
      description: A short description of the feature
```

2022-02-13 18:19 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/enhancement.yml
> +        step back and describe what you are trying to achieve.
💯

2022-02-13 18:20 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/enhancement.yml
> +      description: What dialect you expect to add this feature?
```suggestion
      description: If the enhancement relates to a particular dialect, which one?
```

2022-02-13 18:20 UTC, barrywhart commented on .github/ISSUE_TEMPLATE/enhancement.yml
> +        - label: Yes I am willing to submit a PR!
Same suggestion as for the bug template.

2022-02-13 18:21 UTC, barrywhart submitted a review, later dismissed
This looks nice! I didn't know GitHub supported this.

I'd like @tunetheweb to review this as well, since he has worked a lot in this area and is often the first person to look the issues list.

2022-02-14 02:26 UTC, zhongjiajie commented
> 

FYI @barrywhart ,  I make some changed base on you suggstion in 23faff7, I think is ready to go, please take a look @tunetheweb

2022-02-14 10:18 UTC, alanmcruickshank approved these changes
I don't think there's a good way of testing these in advance - but these look like a great improvement and I'm happy to iterate on from here 👍

2022-02-14 10:20 UTC, tunetheweb commented
I was going to have a look at it in my fork. Gimme an hour or two to do that.

2022-02-14 10:22 UTC, zhongjiajie commented
> I add example issue chooser in https://github.com/zhongjiajie/sqlfluff/issues/new/choose, PTAL @alanmcruickshank @tunetheweb @barrywhart

@tunetheweb I have a test in my own fork, maybe you could take a look on it.

2022-02-14 13:55 UTC, tunetheweb requested changes
This is excellent. Never knew about this functionality in GitHub.

I do have a few suggestions though.

2022-02-15 02:48 UTC, zhongjiajie commented
Hi @tunetheweb @barrywhart @alanmcruickshank , I upgrade this PR right now. PTAL

2022-02-15 05:57 UTC, tunetheweb approved these changes
LGTM!

2022-02-15 05:57 UTC, merged

2022-02-15 06:36 UTC, zhongjiajie commented
Thanks~

2022-02-15 06:37 UTC, tunetheweb commented
Thank you!

Can we do same for PRs?

2022-02-15 06:39 UTC, zhongjiajie commented
> Can we do same for PRs?

No, we can not, GitHub do not support this, at least for now

2022-02-15 06:42 UTC, tunetheweb commented
> No, we can not, GitHub do not support this, at least for now

😞 Hopefully soon! Would be very useful there too.

2022-02-15 06:47 UTC, zhongjiajie commented
I check our issue creator, it looks great now 👍 
<img width="1881" alt="image" src="https://user-images.githubusercontent.com/15820530/154007445-c21038ac-5efd-4278-80ae-89f9d6fd034c.png">