Draft release of 0.10.1
sqlfluff/sqlfluff pull request #2637
Opened 2022-02-14 14:25 UTC by alanmcruickshank

Draft release of 0.10.1

2022-02-14 15:07 UTC, tunetheweb approved these changes
LGTM - assuming you'll do a final sync up with latest merges before merging.

2022-02-14 15:58 UTC, barrywhart approved these changes

2022-02-15 06:19 UTC, tunetheweb requested changes
This should not be merged until #2652 is merged as we've introduced a bug since 0.10.0 that we need to fix before releasing 0.10.1.

2022-02-15 16:37 UTC, barrywhart approved these changes
Looks good to me -- ready for release!

2022-02-16 12:26 UTC, merged