Redshift: add [ALTER/CREATE/DROP] PROCDURE segments
sqlfluff/sqlfluff pull request #2774
Opened 2022-03-03 12:53 UTC by rpr-ableton

### Brief summary of the change made

What the title says :slightly_smiling_face: 

Adding relevant segments for procedures. It diverges slightly from postgresql due to the additional optional `argmode` in the parameters list.

### Are there any other side effects of this change that we should be aware of?

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-03-03 21:01 UTC, barrywhart commented
@rpr-ableton: One of the tests is failing with a parse error. Can you look into it?

2022-03-04 08:05 UTC, rpr-ableton commented
Hey @barrywhart, for sure! I naively assumed that everything would be good to go since the yaml generated from `generate_parse_fixtures` looked good :sweat_smile:

I have some time set aside for sqlfluff this afternoon.

2022-03-04 11:56 UTC, tunetheweb requested changes

2022-03-04 14:25 UTC, rpr-ableton commented
@tunetheweb i've adopted the changes you suggested, thanks for that! Let me know if you see space for any further cleanup while we're at it :smile: 

> This seems to be causing the failure. Weirdly it works running the generate in python with this syntax, but not within tox (whether within GitHub Action or even on my own machine). Don't understand why as it should be the same. Very odd...

I'm not sure what to do about that one tbh. Should I try to find another way to express this logic?

2022-03-04 16:43 UTC, tunetheweb commented
This seems to work:

```py
    type = "procedure_parameter_list"
    # Odd syntax, but prevents eager parameters being confused for data types
    _param_type = OneOf("REFCURSOR", Ref("DatatypeSegment"))
    match_grammar = Bracketed(
        Sequence(
            OneOf(Ref("ParameterNameSegment"),exclude=_param_type,optional=True),
            Ref("ArgModeSegment",optional=True),
            _param_type,
            AnyNumberOf(
                Sequence(
                    Ref("CommaSegment"),
                    OneOf(Ref("ParameterNameSegment"),exclude=_param_type,optional=True),
                    Ref("ArgModeSegment",optional=True),
                    _param_type,
                ),
            ),
            optional=True,
        ),
    )
```

2022-03-04 17:26 UTC, tunetheweb commented on src/sqlfluff/dialects/dialect_redshift.py
> +    )
```suggestion
    type = "procedure_parameter_list"
    # Odd syntax, but prevents eager parameters being confused for data types
    _param_type = OneOf("REFCURSOR", Ref("DatatypeSegment"))
    match_grammar = Bracketed(
        Sequence(
            OneOf(Ref("ParameterNameSegment"),exclude=_param_type,optional=True),
            Ref("ArgModeSegment",optional=True),
            _param_type,
            AnyNumberOf(
                Sequence(
                    Ref("CommaSegment"),
                    OneOf(Ref("ParameterNameSegment"),exclude=_param_type,optional=True),
                    Ref("ArgModeSegment",optional=True),
                    _param_type,
                ),
            ),
            optional=True,
        ),
    )
```

2022-03-04 17:30 UTC, rpr-ableton commented
That doesn't quite work as `ParameterNameSegment` and `ArgModeGrammar` can be swapped around in position.

Something like this should do the trick:

```    type = "procedure_parameter_list"
    # Odd syntax, but prevents eager parameters being confused for data types
    _param_type = OneOf("REFCURSOR", Ref("DatatypeSegment"))
    match_grammar = Bracketed(
        Sequence(
            AnyNumberOf(
                OneOf(Ref("ParameterNameSegment"),exclude=_param_type),
                Ref("ArgModeGrammar"),
                optional=True,
            ),
            _param_type,
            AnyNumberOf(
                Sequence(
                    Ref("CommaSegment"),
                    AnyNumberOf(
                        OneOf(Ref("ParameterNameSegment"),exclude=_param_type),
                        Ref("ArgModeGrammar"),
                        optional=True,
                    ),
                    _param_type,
                ),
            ),
            optional=True,
        ),
    )```

2022-03-04 17:39 UTC, tunetheweb commented
What about this slight variation?

```py
    type = "procedure_parameter_list"
    # Odd syntax, but prevents eager parameters being confused for data types
    _param_type = OneOf("REFCURSOR", Ref("DatatypeSegment"))
    match_grammar = Bracketed(
        Sequence(
            AnyNumberOf(
                Ref("ParameterNameSegment"),
                Ref("ArgModeSegment"),
                exclude=_param_type,
                max_times_per_element=1,
            ),
            _param_type,
            AnyNumberOf(
                Sequence(
                    Ref("CommaSegment"),
                    AnyNumberOf(
                        Ref("ParameterNameSegment"),
                        Ref("ArgModeSegment"),
                        exclude=_param_type,
                        max_times_per_element=1,
                    ),
                    _param_type,
                ),
            ),
            optional=True,
        ),
    )
```

Testing it now and then will commit so it makes 0.11.0 which I'm about to release.

2022-03-04 18:11 UTC, tunetheweb commented
Woo hoo that worked. Presume you're happy to merge this @rpr-ableton ?

2022-03-04 18:11 UTC, tunetheweb approved these changes

2022-03-04 18:26 UTC, rpr-ableton commented
LGTM, thanks!

2022-03-04 18:28 UTC, merged