Hive: Support dynamic partition insert
sqlfluff/sqlfluff pull request #3126
Opened 2022-04-20 13:41 UTC by barunpuri

### Brief summary of the change made

fixes #3117 
Support dynamic partition insert in hive dialects

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-04-20 13:44 UTC, tunetheweb requested changes

2022-04-20 13:48 UTC, barunpuri commented on test/fixtures/dialects/hive/insert_overwrite_table_dynamic_partition.sql
> +SELECT a, 'test_bar' AS b FROM bar;
You mean test case 3 and 4? 
Case 1 already exists on examples
It's not hard to add case 3 but, is it okay to add grammatically incorrect code(case 4)?

2022-04-20 13:49 UTC, tunetheweb commented on test/fixtures/dialects/hive/insert_overwrite_table_dynamic_partition.sql
> +SELECT a, 'test_bar' AS b FROM bar;
I meant 1 and 3. OK just need to add 3 if 1 already exists.

4 you are correct you shouldn't add.

2022-04-20 14:49 UTC, tunetheweb commented
Could we merge insert_overwrite_table_dynamic_partition_1.sql and insert_overwrite_table_dynamic_partition_2.sql? It's fine to have multiple SQL statements in the same file (semicolon-separated) - in fact it's preferred to keep related test case together!

2022-04-21 00:18 UTC, barunpuri commented
> Could we merge insert_overwrite_table_dynamic_partition_1.sql and insert_overwrite_table_dynamic_partition_2.sql? It's fine to have multiple SQL statements in the same file (semicolon-separated) - in fact it's preferred to keep related test case together!

Of course, I merged examples. Thank you for your kindly review

2022-04-21 08:34 UTC, tunetheweb approved these changes

2022-04-21 08:50 UTC, merged