Hive: support `CLUSTER`, `DISTRIBUTE`, `SORT BY`
sqlfluff/sqlfluff pull request #3304
Opened 2022-05-10 12:59 UTC by barunpuri

### Brief summary of the change made

fixes #3187
support cluster, distribute, sort by

### Are there any other side effects of this change that we should be aware of?
None

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-05-10 18:00 UTC, tunetheweb requested changes

2022-05-11 00:31 UTC, barunpuri commented on src/sqlfluff/dialects/dialect_hive.py
> +        insert=[Ref.keyword("CLUSTER"), Ref.keyword("DISTRIBUTE"), Ref.keyword("SORT")],
There's only keyword "ORDER" so isn't it better to match the format with the existing one?
https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/dialects/dialect_ansi.py#L2019

2022-05-11 08:27 UTC, tunetheweb commented on src/sqlfluff/dialects/dialect_hive.py
> +        insert=[Ref.keyword("CLUSTER"), Ref.keyword("DISTRIBUTE"), Ref.keyword("SORT")],
Originally there was only `ORDER` in all the sections but we changed that to `ORDER BY` as some people got parsing errors, but guess we missed some places. I think it should be `ORDER BY` everywhere and hence also `CLUSTER BY`...etc.

Would be great if you could clean up those missing `ORDER BY`s too as part of this PR?

2022-05-11 18:57 UTC, tunetheweb approved these changes
LGTM!

2022-05-11 19:27 UTC, merged