Update MySQL keywords
sqlfluff/sqlfluff pull request #3381
Opened 2022-05-20 23:22 UTC by mdahlman

### Brief summary of the change made

SQLFluff had roughly 30 & 40 reserved and unreserved keywords for MySQL respectively.
But the current documented keyword lists are roughly 250 and 500 words for MySQL.
This change adds a new dialect_mysql_keywords.py including all keywords and matching the structure of other dialects.
Additionally, there are some good side effects. Previously, many tests using unquoted reserved keywords passed as valid but should not have. The tests have been updated to respect MySQL's rules. (Use of the unquoted table name "table" was the main culprit.)

As always, I'll be keen for feedback both on the structure code as well as the clarity of the comments.

### Are there any other side effects of this change that we should be aware of?
No side effects beyond changes to MySQL tests.

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-05-21 07:09 UTC, tunetheweb requested changes
Looks good! Can't believe all those `FROM table` statements :-)

Few minor tweaks, and then can merge.

2022-05-21 14:01 UTC, mdahlman commented on src/sqlfluff/dialects/dialect_mysql.py
>  mysql_dialect.sets("unreserved_keywords").update(
I moved it into the keywords file. But still with a comment there. See what you think.

2022-05-22 10:17 UTC, tunetheweb approved these changes
LGTM!

2022-05-22 10:17 UTC, tunetheweb commented on src/sqlfluff/dialects/dialect_mysql.py
> +# Remove this reserved keyword to avoid issue in create_table_primary_foreign_keys.sql
```suggestion
# Remove this reserved keyword to avoid issue in create_table_primary_foreign_keys.sql
# TODO - resolve this properly
```

2022-05-22 10:38 UTC, merged