SparkSQL: Update terminator grammar for `HAVING`, `WHERE`, `GROUP BY`
sqlfluff/sqlfluff pull request #3526
Opened 2022-06-30 19:53 UTC by R7L208

### Brief summary of the change made

- fixes #3484
- updates terminator grammar for various clauses to include `DISTRIBUTE BY`, `CLUSTER BY`, and `SORT BY`

### Are there any other side effects of this change that we should be aware of?
- Update terminator in `HAVING` for Snowflake, Ansi, and Hive
  - add terminator grammar that is defined in each dialect once
- Update terminator in `GROUP BY` for Snowflake, Ansi, and Hive
  - add terminator grammar that is defined in each dialect once

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-06-30 22:10 UTC, tunetheweb requested changes
Change looks could but could I ask for one addition? It may turn out to be a bit of effort so understand if you'd prefer to merge as is.

2022-07-01 14:00 UTC, tunetheweb commented on src/sqlfluff/dialects/dialect_sparksql.py
> +    ),
Well Group By will now with this PR :-)

Agree Having doesn't (yet?) so can either leave that, or clean up for consistency.

2022-07-01 14:03 UTC, R7L208 commented on src/sqlfluff/dialects/dialect_sparksql.py
> +    ),
I'll clean up Having as well. It's implemented in a few other dialects similar by overriding the entire class

:)

2022-07-01 18:48 UTC, tunetheweb approved these changes
So much code clean up - I love it!!

2022-07-01 20:46 UTC, merged