SPARKSQL: Add Delta Lake Constraints syntax to `ALTER TABLE`
sqlfluff/sqlfluff pull request #3643
Opened 2022-07-20 17:09 UTC by R7L208

### Brief summary of the change made

This adds an additional `Sequence` to the `AlterTableStatementSegment` in SparkSQL dialect to support [Delta Lake Constraints](https://docs.delta.io/latest/delta-constraints.html#constraints)

### Are there any other side effects of this change that we should be aware of?
This also fixes two bugs in `AlterTableStatementSegment` with regarding to `DROP NOT NULL`.
- Split "NOT NULL" into two keywords -> "NOT", "NULL"
- Added "DROP" to the `exclude` argument for the `ColumnReferenceSegment` so that it does not match as a column

### Pull Request checklist
- [X] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-07-20 20:20 UTC, tunetheweb requested changes

2022-07-21 13:26 UTC, R7L208 commented on src/sqlfluff/dialects/dialect_sparksql.py
> +                Bracketed(Anything(), optional=True),
I think we need to be deliberately lax. Any expression or function (or combination of the two) that will evaluate to a Boolean is allowed here

2022-07-21 14:03 UTC, tunetheweb commented on src/sqlfluff/dialects/dialect_sparksql.py
> +                Bracketed(Anything(), optional=True),
Would `Ref("ExpressionSegment")` not do that?

2022-07-21 14:25 UTC, R7L208 commented on src/sqlfluff/dialects/dialect_sparksql.py
> +                Bracketed(Anything(), optional=True),
Yeh, that would. Great callout. I'll update and push the changes

2022-07-21 16:51 UTC, tunetheweb approved these changes

2022-07-21 16:51 UTC, merged