ignore functions with more than one element ...
sqlfluff/sqlfluff pull request #3792
Opened 2022-08-26 22:12 UTC by fmms

### Brief summary of the change made
fixes #3583 

### Are there any other side effects of this change that we should be aware of?

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-08-28 22:54 UTC, tunetheweb requested changes

2022-08-28 22:54 UTC, tunetheweb commented on src/sqlfluff/rules/L010.py
> +        # SUM() should be modified. However, dbo.myScalar() must not be modified.
I found this difficult to follow. Would it be easier to just say something like this:

```suggestion
        # Used by L030 (that inherits from this rule)
        # If it's a qualified function_name (i.e with more than one part to
        # function_name). Then it is likely an existing user defined function (UDF)
        # which are case sensitive so ignore for this.
```

I wonder should there be a `include_qualified_functions` option in this (defaulted to `false`)?

Also, I think in some SQL dialects there might be a `SYS` schema or such like that contains the system functions, which are case insensitive? Then again not sure if there's a good reason to use that, so maybe fine to ignore that edge case.

2022-08-28 22:54 UTC, tunetheweb commented on test/fixtures/rules/std_rule_cases/L030.yml
>  test_fail_fully_qualified_function_mixed_functions:
```suggestion
test_pass_fully_qualified_function_mixed_functions:
```

2022-08-28 22:54 UTC, tunetheweb commented on test/fixtures/rules/std_rule_cases/L030.yml
>  test_fail_func_name_templated_literal_mix:
```suggestion
test_pass_func_name_templated_literal_mix:
```

2022-09-12 21:51 UTC, barrywhart commented
@tunetheweb: Could you take another look at this since you'd requested changes on it?

2022-09-12 21:56 UTC, tunetheweb approved these changes

2022-09-12 22:13 UTC, merged