Load the full dbt manifest
sqlfluff/sqlfluff pull request #3926
Opened 2022-10-06 14:37 UTC by davajm

### Brief summary of the change made

Currently, the manifest loading process is only partially done. The flat [graph](https://docs.getdbt.com/reference/dbt-jinja-functions/graph) context variable is never built, which causes dbt models that utilize the variable to error. 

A typical use case would be iterating over `graph.nodes` inside of a model.

Looking at the [dbt source code](https://github.com/dbt-labs/dbt-core/blob/fa4f9d3d97dd3207720867cb3b493bea3ca58a42/core/dbt/parser/manifest.py#L199). These three steps can be found
* Load the manifest
* Build the flat graph
* Set query header macro hook

Currently, only the first step is done. This PR utilizes [get_full_manifest](https://github.com/dbt-labs/dbt-core/blob/fa4f9d3d97dd3207720867cb3b493bea3ca58a42/core/dbt/parser/manifest.py#L199) so we don't have to reproduce these steps.

fixes #3832
fixes #3771

### Are there any other side effects of this change that we should be aware of?
Not quite sure. Might have some performance impact perhaps.
**Note**: My first PR, and I still quite novice at dbt. Would love feedback on this.

### Pull Request checklist
- [ ] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2022-10-06 14:55 UTC, barrywhart requested changes
What is the potential performance impact of this change?

Could you add a test that would have failed without this fix?

2022-10-07 22:57 UTC, davajm commented
> What is the potential performance impact of this change?
> 
> Could you add a test that would have failed without this fix?

I don't think the performance is affected all that much. My initial worry was that I thought that perhaps the manifest could/would be reloaded for each model, but that obviously does not seem to be the case as it's only loaded once during the  dbt compile. @barrywhart Is there a process in place for more thorough performance testing? Also feel free to point me to any testing material that might be of help.

As for the tests, I'm working on it! I am looking at related issues (I keep finding more) for inspiration. Let me know if any issues comes to mind that might be related to this.

2022-10-08 00:43 UTC, barrywhart commented
There aren't really good performance tests at the dbt project level. Someday we'd like to have a sizable, standard dbt project to test with. It's probably not necessary to run a sophisticated performance test, but if you could add a log message before and after the changed code and tell us the difference in timing (before and after the change), that'd be helpful. (Also tell us the approximate number of SQL files in your dbt project.)

About testing, you may be able to simply add a new SQL file and include it in the list for this test: https://github.com/sqlfluff/sqlfluff/blob/main/plugins/sqlfluff-templater-dbt/test/templater_test.py#L64L90

2022-10-09 12:39 UTC, barrywhart approved these changes

2022-10-09 13:23 UTC, merged