fix(L059): allows configuring prefer_quoted_keywords to deconflict with L029
sqlfluff/sqlfluff pull request #4396
Opened 2023-02-15 17:43 UTC by timcosta

### L059 supports requiring all keywords to be quoted
Fixes #4310

### Are there any other side effects of this change that we should be aware of?
Default behavior should remain the same, new behavior is behind a flag that defaults to off

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2023-02-19 12:55 UTC, WittierDinosaur commented on src/sqlfluff/core/rules/config_info.py
> +            "If ``True``, requires every keyword to be quoted. "
To reduce ambiguity, can you change this to `every keyword used as an identifier`?

2023-02-19 12:56 UTC, WittierDinosaur commented on src/sqlfluff/rules/L059.py
> +        print("identifier_is_quoted", identifier_is_quoted)
can you remove the print statements?

2023-02-19 13:05 UTC, WittierDinosaur requested changes
Linting tests failing, please run `black`

2023-03-06 17:36 UTC, WittierDinosaur commented
Still one open comment

2023-03-15 14:06 UTC, timcosta commented
updated - new test cases were still referring to L059 instead of RF06 since PR predated the rule rewrite.

2023-04-03 18:50 UTC, timcosta commented
This PR should pass all checks, but will need to be re-run manually by someone with more rights than I once the github actions incident is over. All checks are passing locally on the various python versions, and passed in CI too before i squashed all of the tiny commits.

2023-04-05 09:32 UTC, WittierDinosaur approved these changes
LGTM

2023-04-05 09:44 UTC, merged