TSQL: `CREATE EXTERNAL FILE FORMAT`
sqlfluff/sqlfluff pull request #4647
Opened 2023-03-31 12:20 UTC by keen85

### Brief summary of the change made
fixes #4610

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2023-04-01 20:10 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +            optional=False,
optional defaults to false

2023-04-01 20:11 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +            OneOf(
this OneOf isn't needed

2023-04-01 20:11 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +            OneOf(
this OneOf isn't needed

2023-04-01 20:12 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +            OneOf(
This OneOf isn't needed

2023-04-01 20:15 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +        Sequence(
Most of these can be condensed into one Sequence. The ones that equal quotedliteral can have the options wrapped in a OneOf()
OneOf("FIELD_TERMINATOR", "STRING_DELIMITER") etc

2023-04-01 20:15 UTC, WittierDinosaur requested changes
Left a few comments. There are more places where there are similary unnecessary OneOf's and optional=False

2023-04-02 11:58 UTC, keen85 commented
@WittierDinosaur thanks for the valuable input.

2023-04-03 10:59 UTC, WittierDinosaur commented on src/sqlfluff/dialects/dialect_tsql.py
> +                    AnyNumberOf(
Last one - you don't need this AnyNumberOf

2023-04-04 10:41 UTC, WittierDinosaur approved these changes
LGTM

2023-04-04 10:49 UTC, merged