Caplitalisation: Add camelCase
sqlfluff/sqlfluff pull request #5777
Opened 2024-04-16 18:08 UTC by WittierDinosaur

### Brief summary of the change made
This PR adds camelCase to the extended capiltalisation policy. Added tests to cov er its functionality.

### Are there any other side effects of this change that we should be aware of?
Yes. I added snake case to the refuted cases if the first letter is uppercase. It seems like an oversight that it was never there. I changed the snake case tests to factor this in

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2024-04-18 21:25 UTC, alanmcruickshank requested changes
Can you elaborate in the docs? I _think_ the logic makes sense but I'm having trouble checking that it's consistent without it clearly documenting what it's _supposed_ to do.

2024-04-18 21:25 UTC, alanmcruickshank commented on src/sqlfluff/core/rules/config_info.py
>              "This is separate from ``capitalisation_policy`` as it should not be "
I think the precedence rules here aren't very easy to guess. I think from running through the examples below, that I understand the logic - but I think we should document it here.

If nothing else - someone will ask on the slack channel and I'd like to be able to point them to something to explain _why_ the default config is acting the way that it is.

2024-05-14 19:15 UTC, nstringham commented
Any update on this?

2024-06-01 14:42 UTC, atishay commented
How can we help getting this merged?

2024-06-09 19:26 UTC, alanmcruickshank approved these changes
LGTM. I agree there's some strange inference on fixing camel case situations, but I don't have any better ideas!

2024-06-09 19:36 UTC, merged