Improve typing/coverage for linter module
sqlfluff/sqlfluff pull request #580
Opened 2020-11-24 22:07 UTC by pwildenhain

Related to #488 

Finished adding coverage -- I think this is as good as this one will get (for now)

Going to add some type hints before requesting a review.

Side note (@alanmcruickshank)
There was a decent amount of untested code in the `Linter.fix()` method but I didn't address it since it doesn't actually seem like it's used in the CLI. Is this accurate?

2020-11-26 11:06 UTC, alanmcruickshank requested changes
I'd like to keep the `.tree()` method because I think it's going to be useful for the API. Can we instead get a test case around it?

Even better would be to test the API example (in `examples/`) directly if you can work out a way of doing that nicely?

2020-11-26 11:06 UTC, alanmcruickshank commented on test/core/linter_test.py
> +        result.check_tuples()
Nice!

2020-11-27 15:27 UTC, pwildenhain commented
Also, @alanmcruickshank did something happen with codecov.io? I haven't seen to code coverage diff being reported on the last couple PRs

2020-11-28 10:50 UTC, dmateusp reviewed
heroic effort 🎉

2020-11-28 10:50 UTC, dmateusp commented on src/sqlfluff/core/errors.py
> +CheckTuple = Tuple[str, int, int]
There's type aliases in Python? whaat 🤯

2020-11-30 19:19 UTC, alanmcruickshank commented
> Also, @alanmcruickshank did something happen with codecov.io? I haven't seen to code coverage diff being reported on the last couple PRs

No idea on this - good catch. I'll try removing the plugin and re-adding it.

2020-12-04 21:05 UTC, pwildenhain commented
@alanmcruickshank This is good to go I think 🙆‍♂️

2020-12-05 13:03 UTC, alanmcruickshank approved these changes

2020-12-05 13:03 UTC, merged