Postgres: Allow negative integers in sequences
sqlfluff/sqlfluff pull request #6111
Opened 2024-08-26 14:20 UTC by WittierDinosaur

### Brief summary of the change made
Fixes #5908

### Are there any other side effects of this change that we should be aware of?
No

### Pull Request checklist
- [x] Please confirm you have completed any of the necessary steps below.

- Included test cases to demonstrate any code changes, which may be one or more of the following:
  - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
  - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
  - Full autofix test cases in `test/fixtures/linter/autofix`.
  - Other.
- Added appropriate documentation for the change.
- Created GitHub issues for any relevant followup/future enhancements if appropriate.

2024-08-28 04:14 UTC, keraion requested changes
I'd suggest changing all the `NegativeSegment`s with `SignedSegmentGrammar`.

2024-08-28 04:14 UTC, keraion commented on src/sqlfluff/dialects/dialect_postgres.py
> +            Ref("NegativeSegment", optional=True),
The `NegativeSegment` should be replaced with `SignedSegmentGrammar` as values like `+4` are also allowed.

2024-09-07 18:13 UTC, WittierDinosaur commented
@keraion addressed 👍

2024-09-08 00:55 UTC, keraion approved these changes
LGTM

2024-09-08 01:07 UTC, merged