Add Surfline to SQLFluff in the Wild
sqlfluff/sqlfluff pull request #994
Opened 2021-04-23 19:18 UTC by GClunies

Linting brah! 🤙🏽  🏄🏽

2021-04-23 19:25 UTC, barrywhart approved these changes
🎉 💯

2021-04-23 21:12 UTC, NiallRees commented on docs/source/inthewild.rst
> +- `Surline <https://www.surfline.com/>`_'s Analytics Engineering team
Just a typo here 😁

2021-04-23 21:12 UTC, NiallRees requested changes
Surline - steaks directly to your door?

2021-04-23 21:45 UTC, GClunies commented on docs/source/inthewild.rst
> +- `Surline <https://www.surfline.com/>`_'s Analytics Engineering team
Well done! 🤣  🐮

2021-04-23 21:46 UTC, GClunies commented
Well done @NiallRees! 🤣  🐮

2021-04-24 08:29 UTC, NiallRees approved these changes

2021-04-24 08:29 UTC, merged